// docs/ledger-sim.md: one table row per case, then the screens of each case as the device showed them.
import type { CaseResult } from './drive.ts';

export type Report = { date: string; model: string; ledger: string; path: string; appVersion: string; results: CaseResult[] };

const OUTCOME_TEXT = {
  'clear-sign': 'clear text',
  'blind-sign': 'blind signing required',
  error: 'error',
} as const;

export function renderReport(report: Report): string {
  const lines = [
    '# Ledger simulation',
    '',
    `Generated by \`pnpm ledger-sim\` on ${report.date}. Ledger Solana app ${report.appVersion} on the Speculos emulator`,
    `(${report.model}), blind signing off (the default). The device key is Speculos' public test seed at`,
    `\`${report.path}\`: \`${report.ledger}\`. Every other address is a throwaway one; nothing is sent to a network.`,
    '',
    'Outcome: "clear text" means the app parsed the transaction, showed the fields below and returned a signature that',
    'verifies against the message. "blind signing required" means the app refused to parse it.',
    '',
    '| Case | Ledger holds | Lifetime | Variant | Outcome | Inspector |',
    '| --- | --- | --- | --- | --- | --- |',
    ...report.results.map(
      (r) =>
        `| ${r.case.title} | ${r.case.role} | ${r.case.lifetime} | ${r.case.variant} | ${OUTCOME_TEXT[r.outcome]}${
          r.outcome === 'error' ? ` (0x${r.status.toString(16)})` : ''
        } | ${r.inspectorError ?? 'accepted'} |`,
    ),
    '',
    '## Screens',
    '',
  ];
  for (const r of report.results) {
    lines.push(`### ${r.case.id}`, '', '```text');
    for (const screen of r.screens) lines.push(joinScreen(screen));
    lines.push('```', '');
  }
  return lines.join('\n');
}

/** "Title | value" with a wrapped address joined back into one string. */
export function joinScreen(lines: readonly string[]): string {
  const [title = '', ...rest] = lines;
  return rest.length === 0 ? title : `${title} | ${rest.join('')}`;
}
